In [10]:
import pandas as pd

# Fact Table: Contains measurable data and keys to dimension tables
sales = pd.DataFrame({
    "sales_id": [1, 2, 3, 4],
    "product_id": [101, 102, 101, 103],
    "customer_id": [1, 2, 1, 3],
    "date_id": [1, 1, 2, 2],
    "amount": [50000, 20000, 30000, 15000],
    "quantity": [1, 2, 1, 1]
})

# Product Dimension
product = pd.DataFrame({
    "product_id": [101, 102, 103],
    "product_name": ["Laptop", "Phone", "Tablet"],
    "category": ["Electronics", "Electronics", "Electronics"]
})

# Customer Dimension
customer = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "customer_name": ["Amit", "Riya", "John"],
    "city": ["Bangalore", "Mumbai", "Delhi"]
})

# Date Dimension
date = pd.DataFrame({
    "date_id": [1, 2],
    "month": ["Jan", "Feb"],
    "year": [2024, 2024]
})

In [11]:
# Merging the Fact table with Product and Customer Dimensions
df = sales.merge(product, on="product_id") \
          .merge(customer, on="customer_id") \
          .merge(date, on="date_id")

df

,sales_id,product_id,customer_id,date_id,amount,quantity,product_name,category,customer_name,city,month,year
0,1,101,1,1,50000,1,Laptop,Electronics,Amit,Bangalore,Jan,2024
1,2,102,2,1,20000,2,Phone,Electronics,Riya,Mumbai,Jan,2024
2,3,101,1,2,30000,1,Laptop,Electronics,Amit,Bangalore,Feb,2024
3,4,103,3,2,15000,1,Tablet,Electronics,John,Delhi,Feb,2024

In [13]:
final_summary = df.groupby("product_name")["amount"].sum()
print(final_summary)

product_name
Laptop    80000
Phone     20000
Tablet    15000
Name: amount, dtype: int64

In [14]:
# 2. Total sales amount per Customer
df.groupby("customer_name")["amount"].sum()

customer_name
Amit    80000
John    15000
Riya    20000
Name: amount, dtype: int64

In [15]:
# 3. Total sales amount per Month
df.groupby("month")["amount"].sum()

month
Feb    45000
Jan    70000
Name: amount, dtype: int64

In [16]:
# Sorting by amount in descending order and taking the top 1 record
df.sort_values("amount", ascending=False).head(1)

,sales_id,product_id,customer_id,date_id,amount,quantity,product_name,category,customer_name,city,month,year
0,1,101,1,1,50000,1,Laptop,Electronics,Amit,Bangalore,Jan,2024