Task 1 – Create Fact Table
Create a sales fact table with columns:
Text id="8gpbv0"
Copy code
sales_id, product_id, customer_id, date_id, amount, quantity
📝 Task 2 – Create Dimension Tables
Product Table
Text id="qbwn1r"
Copy code
product_id, product_name, category
Customer Table
Text id="1n5zoo"
Copy code
customer_id, customer_name, city
Date Table
Text id="9luf6h"
Copy code
date_id, month, year
🔗 PART 2 – BUILD STAR SCHEMA
📝 Task 3 – Join Tables
Join all tables to create one dataset:
✔ sales + product
✔ + customer
✔ + date
👉 Final dataset should contain:
Text id="94q3gc"
Copy code
product_name, customer_name, city, month, amount
📊 PART 3 – ANALYTICS TASKS
🟢 Basic Tasks
1️⃣ Total sales per product
2️⃣ Total sales per customer
🟡 Intermediate Tasks
3️⃣ Total sales per city
4️⃣ Total sales per month
🔴 Advanced Tasks
5️⃣ Find top product (highest sales)
6️⃣ Find top customer
7️⃣ Find average sales per transaction
8️⃣ Find total quantity sold per product

In [1]:
import pandas as pd

In [2]:
sales = pd.DataFrame({
    "sales_id": [1,2,3,4],
    "product_id": [101,102,101,103],
    "customer_id": [1,2,1,3],
    "date_id": [1,1,2,2],
    "amount": [50000,20000,30000,15000],
    "quantity":[1,2,1,1]
})

sales

   sales_id  product_id  customer_id  date_id  amount  quantity
0         1         101            1        1   50000         1
1         2         102            2        1   20000         2
2         3         101            1        2   30000         1
3         4         103            3        2   15000         1

In [3]:
product = pd.DataFrame({
    "product_id": [101,102,103],
    "product_name": ["Laptop"," Phone", "Tablet"],
    "category": ["Electronics", "Electronics", "Electronics"]
})

product

   product_id product_name     category
0         101       Laptop  Electronics
1         102        Phone  Electronics
2         103       Tablet  Electronics

In [4]:
customer = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "customer_name": ["Amit", "Riya", "John"],
    "city": ["Bangalore", "Mumbai", "Delhi"]
})

customer

   customer_id customer_name       city
0            1          Amit  Bangalore
1            2          Riya     Mumbai
2            3          John      Delhi

In [9]:
date = pd.DataFrame({
    "date_id": [1, 2],
    "month": ["January", "February"],
    "year": [2024, 2024]
})

date

   date_id     month  year
0        1   January  2024
1        2  February  2024

In [11]:
df = (sales
     .merge(product, on="product_id")
     .merge(customer, on="customer_id")
     .merge(date, on="date_id"))

df[["product_name", "customer_name", "city", "month", "amount"]]

  product_name customer_name       city     month  amount
0       Laptop          Amit  Bangalore   January   50000
1        Phone          Riya     Mumbai   January   20000
2       Laptop          Amit  Bangalore  February   30000
3       Tablet          John      Delhi  February   15000

In [14]:
df.groupby("product_name")["amount"].sum().reset_index()

  product_name  amount
0        Phone   20000
1       Laptop   80000
2       Tablet   15000

In [15]:
df.groupby("customer_name")["amount"].sum().reset_index()

  customer_name  amount
0          Amit   80000
1          John   15000
2          Riya   20000

In [16]:
df.groupby("city")["amount"].sum().reset_index()

        city  amount
0  Bangalore   80000
1      Delhi   15000
2     Mumbai   20000

In [17]:
df.groupby("month")["amount"].sum().reset_index()

      month  amount
0  February   45000
1   January   70000

In [18]:
(df.groupby("product_name")["amount"]
   .sum()
   .reset_index()
   .sort_values(by="amount", ascending=False)
   .head(1))

  product_name  amount
1       Laptop   80000

In [19]:
(df.groupby("customer_name")["amount"]
   .sum()
   .reset_index()
   .sort_values(by="amount", ascending=False)
   .head(1))

  customer_name  amount
0          Amit   80000

In [20]:
df["amount"].mean()

np.float64(28750.0)

In [21]:
df.groupby("product_name")["quantity"].sum().reset_index()

  product_name  quantity
0        Phone         2
1       Laptop         2
2       Tablet         1