In [1]:
!nproc #check no. of cpus runnin

2

In [2]:
!free -h #memory shown as cloud server specification

               total        used        free      shared  buff/cache   available
Mem:            12Gi       753Mi       8.8Gi       1.0Mi       3.2Gi        11Gi
Swap:             0B          0B          0B

In [3]:
print("Running job on cloud compute")

Running job on cloud compute

In [4]:
#data processing job
import pandas as pd
data = {
    "name":["Amit","Riya","John","Sara"],
    "sales":[200,300,150,400]
}
df = pd.DataFrame(data)
df

   name  sales
0  Amit    200
1  Riya    300
2  John    150
3  Sara    400

In [5]:
df.groupby("name")["sales"].sum()

name
Amit    200
John    150
Riya    300
Sara    400
Name: sales, dtype: int64

In [6]:
#simulating large job on cloud
import time
for i in range(5):
    print("Processing batch",i)
    time.sleep(1)

Processing batch 0
Processing batch 1
Processing batch 2
Processing batch 3
Processing batch 4

In [7]:
!pip install pyspark  #use for big data processing

Requirement already satisfied: pyspark in /usr/local/lib/python3.12/dist-packages (4.0.2)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark) (0.10.9.9)

In [8]:
#computing some large process using pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("compute-demo").getOrCreate()
data = [
    (1,"Amit",200),
    (2,"Riya",300),
    (3,"John",150)
]
spark_df = spark.createDataFrame(data,["id","name","sales"])
spark_df.show()

+---+----+-----+
| id|name|sales|
+---+----+-----+
|  1|Amit|  200|
|  2|Riya|  300|
|  3|John|  150|
+---+----+-----+

In [9]:
spark_df.groupBy("name").sum("sales").show()
#similar to Dataproc/EMR jobs in cloud

+----+----------+
|name|sum(sales)|
+----+----------+
|Amit|       200|
|Riya|       300|
|John|       150|
+----+----------+