In [1]:
import pandas as pd
df= pd.DataFrame({
"order_id": [1,2,2,4,5],
"customer_name": ["Amit", None, "Riya", "John", "Sara"],
"email": ["amit@gmail.com","riya@gmail", None, "john@gmail.com","sara@gmail.com"],
"product": ["Laptop", "Phone", "Phone", "Tablet", None],
"amount": [50000,-20000, 20000, None, 30000],
"date": ["2024-01-01","2024-01-02", "wrong_date", "2024-01-04", "2024/01/05"]
})
df

   order_id customer_name           email product   amount        date
0         1          Amit  amit@gmail.com  Laptop  50000.0  2024-01-01
1         2          None      riya@gmail   Phone -20000.0  2024-01-02
2         2          Riya            None   Phone  20000.0  wrong_date
3         4          John  john@gmail.com  Tablet      NaN  2024-01-04
4         5          Sara  sara@gmail.com    None  30000.0  2024/01/05

In [2]:
df.isnull().sum()

order_id         0
customer_name    1
email            1
product          1
amount           1
date             0
dtype: int64

In [3]:
df[df.duplicated()]

Empty DataFrame
Columns: [order_id, customer_name, email, product, amount, date]
Index: []

In [4]:
df[df["amount"]<0]

   order_id customer_name       email product   amount        date
1         2          None  riya@gmail   Phone -20000.0  2024-01-02

In [9]:
df[~df["email"].str.contains("@", na=False)]

   order_id customer_name email product   amount        date
2         2          Riya  None   Phone  20000.0  wrong_date

In [10]:
pd.to_datetime(df["date"],errors='coerce')

0   2024-01-01
1   2024-01-02
2          NaT
3   2024-01-04
4          NaT
Name: date, dtype: datetime64[ns]

In [11]:
df.drop_duplicates(inplace=True)

In [13]:
df["customer_name"].fillna("Unknown", inplace=True)
df["product"].fillna("Unknown", inplace=True)

In [14]:
df["amount"] = df["amount"].apply(lambda x: abs(x) if pd.notnull(x) and x < 0 else x)

In [15]:
df["date"] = pd.to_datetime(df["date"], errors='coerce')

In [16]:
df["email"] = df["email"].apply(lambda x: x if "@" in str(x) else "invalid@email.com")

In [17]:
df = df[df["amount"].notnull()]

In [18]:
df

   order_id customer_name              email  product   amount       date
0         1          Amit     amit@gmail.com   Laptop  50000.0 2024-01-01
1         2       Unknown         riya@gmail    Phone  20000.0 2024-01-02
2         2          Riya  invalid@email.com    Phone  20000.0        NaT
4         5          Sara     sara@gmail.com  Unknown  30000.0        NaT

In [19]:
df.groupby("product")["amount"].sum()

product
Laptop     50000.0
Phone      40000.0
Unknown    30000.0
Name: amount, dtype: float64