import pandas as pd df = pd.DataFrame({ "order_id":[1,2,2,4,5,6], "customer_name":["Amit",None,"Riya","John","Sara","Amit"], "email":["amit@gmail.com","riya@gmail","riya@gmail.com","john@gmail.com","sara@gmail","amit@gmail.com"], "product":["Laptop","Phone","Phone","Tablet",None,"Laptop"], "amount":[50000,-20000,20000,None,30000,50000], "quantity":[1,2,2,1,None,1], "date":["2024-01-01","2024-01-02","wrong_date","2024-01-04","2024/01/05","2024-01-01"] }) df Task 1 – Identify Issues Students must find: ✔ Null values ✔ Duplicate rows ✔ Negative values ✔ Invalid emails ✔ Wrong date formats Task 2 – Fix Data Students must: 1️⃣ Remove duplicate rows 2️⃣ Handle missing values ✔ Replace missing names with "Unknown" ✔ Replace missing product with "Unknown" 3️⃣ Fix negative values ✔ Convert negative amount to positive 4️⃣ Fix email issues ✔ Replace invalid emails with "invalid@email.com" 5️⃣ Fix date column ✔ Convert to proper date format 6️⃣ Remove rows with missing amount or quantity Task 3 – Verify Data Students must check: ✔ No null values ✔ No duplicates ✔ All amounts > 0 ✔ Dates are valid Task 4 – Perform Analysis Students must calculate: 1️⃣ Total sales per product 2️⃣ Total sales per customer 3️⃣ Total quantity sold 4️⃣ Top product 5️⃣ Top customer

In [1]:
import pandas as pd

df = pd.DataFrame({
    "order_id":[1,2,2,4,5,6],
    "customer_name":["Amit",None,"Riya","John","Sara","Amit"],
    "email":["amit@gmail.com","riya@gmail","riya@gmail.com","john@gmail.com","sara@gmail","amit@gmail.com"],
    "product":["Laptop","Phone","Phone","Tablet",None,"Laptop"],
    "amount":[50000,-20000,20000,None,30000,50000],
    "quantity":[1,2,2,1,None,1],
    "date":["2024-01-01","2024-01-02","wrong_date","2024-01-04","2024/01/05","2024-01-01"]
})

df

,order_id,customer_name,email,product,amount,quantity,date
0,1,Amit,amit@gmail.com,Laptop,50000.0,1.0,2024-01-01
1,2,None,riya@gmail,Phone,-20000.0,2.0,2024-01-02
2,2,Riya,riya@gmail.com,Phone,20000.0,2.0,wrong_date
3,4,John,john@gmail.com,Tablet,NaN,1.0,2024-01-04
4,5,Sara,sara@gmail,None,30000.0,NaN,2024/01/05
5,6,Amit,amit@gmail.com,Laptop,50000.0,1.0,2024-01-01

In [2]:
df.isnull().sum()

order_id         0
customer_name    1
email            0
product          1
amount           1
quantity         1
date             0
dtype: int64

In [3]:
df[df.duplicated()]

Empty DataFrame
Columns: [order_id, customer_name, email, product, amount, quantity, date]
Index: []

In [4]:
df[df["amount"] < 0]

   order_id customer_name       email product   amount  quantity        date
1         2          None  riya@gmail   Phone -20000.0       2.0  2024-01-02

In [5]:
df[~df["email"].str.contains("@", na=False)]

Empty DataFrame
Columns: [order_id, customer_name, email, product, amount, quantity, date]
Index: []

In [6]:
pd.to_datetime(df["date"], errors='coerce')

0   2024-01-01
1   2024-01-02
2          NaT
3   2024-01-04
4          NaT
5   2024-01-01
Name: date, dtype: datetime64[ns]

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df["customer_name"] = df["customer_name"].fillna("Unknown")
df["product"] = df["product"].fillna("Unknown")

In [9]:
df["amount"] = df["amount"].apply(lambda x: abs(x) if pd.notnull(x) and x < 0 else x)

In [10]:
df["email"] = df["email"].apply(
    lambda x: x if pd.notnull(x) and "@" in x and "." in x else "invalid@email.com"
)

In [11]:
df["date"] = pd.to_datetime(df["date"], errors='coerce')

In [20]:
df = df[df["date"].notnull()]

In [12]:
df = df[df["amount"].notnull() & df["quantity"].notnull()]

In [21]:
print("Null values:\n", df.isnull().sum())
print("\nDuplicates:\n", df.duplicated().sum())
print("\nAny negative amounts:\n", (df["amount"] < 0).sum())
print("\nDates:\n", df["date"])

Null values:
 order_id         0
customer_name    0
email            0
product          0
amount           0
quantity         0
date             0
dtype: int64

Duplicates:
 0

Any negative amounts:
 0

Dates:
 0   2024-01-01
1   2024-01-02
5   2024-01-01
Name: date, dtype: datetime64[ns]

In [14]:
df

,order_id,customer_name,email,product,amount,quantity,date
0,1,Amit,amit@gmail.com,Laptop,50000.0,1.0,2024-01-01
1,2,Unknown,invalid@email.com,Phone,20000.0,2.0,2024-01-02
2,2,Riya,riya@gmail.com,Phone,20000.0,2.0,NaT
5,6,Amit,amit@gmail.com,Laptop,50000.0,1.0,2024-01-01

In [15]:
df.groupby("product")["amount"].sum().reset_index()

  product    amount
0  Laptop  100000.0
1   Phone   40000.0

In [16]:
df.groupby("customer_name")["amount"].sum().reset_index()

  customer_name    amount
0          Amit  100000.0
1          Riya   20000.0
2       Unknown   20000.0

In [17]:
df["quantity"].sum()

np.float64(6.0)

In [18]:
(df.groupby("product")["amount"]
   .sum()
   .reset_index()
   .sort_values(by="amount", ascending=False)
   .head(1))

  product    amount
0  Laptop  100000.0

In [19]:
(df.groupby("customer_name")["amount"]
   .sum()
   .reset_index()
   .sort_values(by="amount", ascending=False)
   .head(1))

  customer_name    amount
0          Amit  100000.0