You are a Data Engineer in an e-commerce company.
Your pipeline is slow and consuming high memory.
Your job is to optimize performance and reduce cost.
📊 PART 1 – CREATE LARGE DATASET
📝 Task 1
Create dataset:
Plain text
order_id, amount, category
Requirements
✔ At least 100,000 rows
✔ Use:
Python
range()
✔ Add duplicate values
✔ Add repeating values (important for caching)
⏱️ PART 2 – SLOW IMPLEMENTATION
📝 Task 2
Use loop-based processing:
✔ Multiply amount * 2
✔ Store in new column result
Measure time
Python
import time
✔ Print execution time
🎯 Expected
👉 This should be slow
⚡ PART 3 – OPTIMIZED IMPLEMENTATION
📝 Task 3
Replace loop with:
✔ Vectorized operation
Python
df["result"] = df["amount"] * 2
Measure time again
👉 Compare with previous step
📊 PART 4 – PERFORMANCE COMPARISON
📝 Task 4
Print:
✔ Loop time
✔ Vectorized time
🎯 Question
👉 Which is faster and why?
🧠 PART 5 – MEMORY OPTIMIZATION
📝 Task 5
Check memory:
Python
df.info()
Optimize datatype
✔ Convert:
Python
int64
PART 9 – CACHING SIMULATION
📝 Task 9
Create function:
✔ Store computed results in dictionary
✔ Use repeated values
Show:
✔ When cache is used
✔ When computation happens
🔁 PART 10 – FINAL OPTIMIZED PIPELINE
📝 Task 10
Create function:
Python
def optimized_pipeline():
Include:
✔ Data loading
✔ Filtering
✔ Vectorization
✔ Memory optimization
✔ Duplicate removal
✔ Caching
📊 PART 11 – FINAL RESULT
Students must show:
✔ Final execution time
✔ Memory usage
✔ Optimized dataset

In [ ]:
import pandas as pd

n = 100000

df = pd.DataFrame({
    "order_id": list(range(n)),
    "amount": [x % 1000 for x in range(n)],   # repeating values (for caching)
    "category": ["A" if x % 2 == 0 else "B" for x in range(n)]
})

# add duplicates
df = pd.concat([df, df.iloc[:5000]], ignore_index=True)

df.head()

   order_id  amount category
0         0       0        A
1         1       1        B
2         2       2        A
3         3       3        B
4         4       4        A

In [ ]:
import time

start = time.time()

result = []
for x in df["amount"]:
    result.append(x * 2)

df["result_loop"] = result

loop_time = time.time() - start
print("Loop Time:", loop_time)

Loop Time: 0.10200357437133789

In [ ]:
start = time.time()

df["result_vectorized"] = df["amount"] * 2

vector_time = time.time() - start
print("Vectorized Time:", vector_time)

Vectorized Time: 0.0032150745391845703

In [ ]:
print("Loop Time:", loop_time)
print("Vectorized Time:", vector_time)

Loop Time: 0.10200357437133789
Vectorized Time: 0.0032150745391845703

Vectorized is faster because it uses optimized C-level operations (NumPy) instead of Python loops.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105000 entries, 0 to 104999
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   order_id           105000 non-null  int64
 1   amount             105000 non-null  int64
 2   category           105000 non-null  object
 3   result_loop        105000 non-null  int64
 4   result_vectorized  105000 non-null  int64
dtypes: int64(4), object(1)
memory usage: 4.0+ MB

In [ ]:
df["amount"] = df["amount"].astype("int32")
df["result_vectorized"] = df["result_vectorized"].astype("int32")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105000 entries, 0 to 104999
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   order_id           105000 non-null  int64
 1   amount             105000 non-null  int32
 2   category           105000 non-null  object
 3   result_loop        105000 non-null  int64
 4   result_vectorized  105000 non-null  int32
dtypes: int32(2), int64(2), object(1)
memory usage: 3.2+ MB

In [ ]:
cache = {}

def compute(x):
    if x in cache:
        print(f"Using cache for {x}")
        return cache[x]

    print(f"Computing for {x}")
    result = x * 2
    cache[x] = result
    return result

# small sample to visualize
sample = pd.DataFrame({"amount": [10,20,10,30,20]})
sample["result"] = sample["amount"].apply(compute)

sample

Computing for 10
Computing for 20
Using cache for 10
Computing for 30
Using cache for 20

   amount  result
0      10      20
1      20      40
2      10      20
3      30      60
4      20      40

In [ ]:
def optimized_pipeline():
    start = time.time()

    # Load
    df = pd.DataFrame({
        "order_id": list(range(100000)),
        "amount": [x % 1000 for x in range(100000)],
        "category": ["A" if x % 2 == 0 else "B" for x in range(100000)]
    })

    # Add duplicates
    df = pd.concat([df, df.iloc[:5000]], ignore_index=True)

    # Remove duplicates
    df = df.drop_duplicates()

    # Filtering
    df = df[df["amount"] > 100].copy()

    # Vectorized computation
    df["result"] = df["amount"] * 2

    # Memory optimization
    df["amount"] = df["amount"].astype("int32")
    df["result"] = df["result"].astype("int32")

    end = time.time()

    print("Final Time:", end - start)
    print("\nFinal Data:")
    print(df.head())

    print("\nMemory Usage:")
    df.info()

    return df

optimized_df = optimized_pipeline()

Final Time: 0.11132645606994629

Final Data:
     order_id  amount category  result
101       101     101        B     202
102       102     102        A     204
103       103     103        B     206
104       104     104        A     208
105       105     105        B     210

Memory Usage:
<class 'pandas.core.frame.DataFrame'>
Index: 89900 entries, 101 to 99999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  89900 non-null  int64
 1   amount    89900 non-null  int32
 2   category  89900 non-null  object
 3   result    89900 non-null  int32
dtypes: int32(2), int64(1), object(1)
memory usage: 2.7+ MB