In [ ]:
import pandas as pd

df = pd.DataFrame({
    "id":[1,2,3],
    "name":["Amit","Riya","John"],
    "email":["amit@gmail.com","riya@gmail.com","john@gmail.com"], #sensitive
    "salary":[50000,60000,55000],   #sensitive
    "account_number":["1234567890","9876543210","1122334455"]   # sensitive
})

df

   id  name           email  salary account_number
0   1  Amit  amit@gmail.com   50000     1234567890
1   2  Riya  riya@gmail.com   60000     9876543210
2   3  John  john@gmail.com   55000     1122334455

In [ ]:
masked_df = df.copy()  # can be human readable

masked_df["email"] = masked_df["email"].apply(lambda x: x[0] + "***@***.com")
masked_df["salary"] = "***MASKED***"
masked_df["account_number"] = masked_df["account_number"].apply(lambda x: "XXXXXX" + x[-4:])

masked_df

   id  name         email        salary account_number
0   1  Amit  a***@***.com  ***MASKED***     XXXXXX7890
1   2  Riya  r***@***.com  ***MASKED***     XXXXXX3210
2   3  John  j***@***.com  ***MASKED***     XXXXXX4455

In [ ]:
def access_data(role):
    if role == "admin":
        print("Admin Access")
        return df

    elif role == "analyst":
        print("Analyst Access")
        return masked_df

    else:
        print("Access Denied")
        return None

In [ ]:
!pip install cryptography

Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography) (3.0)

In [ ]:
from cryptography.fernet import Fernet

key = Fernet.generate_key()
cipher = Fernet(key)

message = "Salary = 50000"

encrypted = cipher.encrypt(message.encode())
decrypted = cipher.decrypt(encrypted).decode()

print("Original:", message)
print("Encrypted:", encrypted)
print("Decrypted:", decrypted)

Original: Salary = 50000
Encrypted: b'gAAAAABpwT_VAI8E8ZGecZJzujdRI603FzGD53KJRD22cLDxcFepswrRT9EBsn4_D1TN7wopycLqumVl4LsPnj0V76v6uCb2Zg=='
Decrypted: Salary = 50000

In [ ]:
def secure_pipeline(role):
    data = access_data(role)

    if data is not None:
        print("Processing data...")
        print(data.head())
    else:
        print("No access → cannot process")

In [ ]:
secure_pipeline("analyst")

Analyst Access
Processing data...
   id  name         email        salary account_number
0   1  Amit  a***@***.com  ***MASKED***     XXXXXX7890
1   2  Riya  r***@***.com  ***MASKED***     XXXXXX3210
2   3  John  j***@***.com  ***MASKED***     XXXXXX4455

In [ ]:
secure_pipeline("admin")

Admin Access
Processing data...
   id  name           email  salary account_number
0   1  Amit  amit@gmail.com   50000     1234567890
1   2  Riya  riya@gmail.com   60000     9876543210
2   3  John  john@gmail.com   55000     1122334455

In [ ]:
secure_pipeline("intern")

Access Denied
No access → cannot process