You are a Data Engineer in an E-commerce company.
You received raw sales data.
Your task is to track, validate, clean, and report data using governance concepts.

PART 1 – CREATE DATA
📝 Task 1
Create a dataset with:
Text id="f2y3mv"
Copy code
id, name, sales
Include:
✔ Duplicate records
✔ Missing values
✔ Negative values
📘 PART 2 – METADATA
📝 Task 2
Create a metadata dictionary with:
✔ table_name
✔ owner
✔ created_date
✔ source
🎯 Question
👉 What is metadata? (write 1–2 lines)
🔗 PART 3 – DATA LINEAGE
📝 Task 3
Create a list to track steps:
Text id="n1joh0"
Copy code
Data Loaded → Data Validated → Data Cleaned → Data Transformed → Report Generated
🎯 Question
👉 What is data lineage?
🔍 PART 4 – DATA VALIDATION
📝 Task 4
Perform checks:
✔ Count null values
✔ Count duplicates
✔ Count negative values
🧹 PART 5 – DATA CLEANING
📝 Task 5
Fix the data:
✔ Remove duplicates
✔ Replace missing names with "Unknown"
✔ Convert negative sales to positive
✔ Remove rows with missing sales
🔄 PART 6 – DATA TRANSFORMATION
📝 Task 6
Add new columns:
Text id="2s3s8d"
Copy code
tax = 10% of sales
total = sales + tax
📊 PART 7 – ANALYSIS
📝 Task 7
Find:
✔ Total

In [ ]:
import pandas as pd
from datetime import datetime

df = pd.DataFrame({
    "id": [1,2,2,4],
    "name":["Amit", None, "Riya", "John"],
    "sales":[50000, -20000, 20000, None]
})

df

   id  name    sales
0   1  Amit  50000.0
1   2  None -20000.0
2   2  Riya  20000.0
3   4  John      NaN

In [ ]:
metadata = {
    "table_name": "sales_data",
    "owner": "data_engineering_team",
    "created_date": str(datetime.now()),
    "source": "csv_file"
}

metadata

{'table_name': 'sales_data',
 'owner': 'data_engineering_team',
 'created_date': '2026-03-21 15:28:38.758408',
 'source': 'csv_file'}

Metadata is data about data. It describes information like source, structure, and ownership of a dataset.

In [ ]:
lineage = [
    "Data Loaded",
    "Data Validated",
    "Data Cleaned",
    "Data Transformed",
    "Report Generated"
]

lineage

['Data Loaded',
 'Data Validated',
 'Data Cleaned',
 'Data Transformed',
 'Report Generated']

Data lineage tracks the flow of data from source to final output, showing how it is processed and transformed.

In [ ]:
validation_report = {
    "null_values": df.isnull().sum().to_dict(),
    "duplicates": int(df.duplicated().sum()),
    "negative_values": int((df["sales"]<0).sum())
}

validation_report

{'null_values': {'id': 0, 'name': 1, 'sales': 1},
 'duplicates': 0,
 'negative_values': 1}

In [ ]:
df = df.drop_duplicates()

df["name"]=df["name"].fillna("Unknown")
df["sales"]=df["sales"].apply(lambda x: abs(x) if pd.notnull(x) else x)
df=df[df["sales"].notnull()]

df

   id     name    sales
0   1     Amit  50000.0
1   2  Unknown  20000.0
2   2     Riya  20000.0

In [ ]:
df["tax"]=df["sales"]*0.1
df["total"]=df["sales"]+df["tax"]

df

   id     name    sales     tax    total
0   1     Amit  50000.0  5000.0  55000.0
1   2  Unknown  20000.0  2000.0  22000.0
2   2     Riya  20000.0  2000.0  22000.0

In [ ]:
result=df.groupby("name")["total"].sum()
result

name
Amit       55000.0
Riya       22000.0
Unknown    22000.0
Name: total, dtype: float64